import {$,api,post,esc,date,badge,empty,stat,table,head,start,bindForm,on,currentUser,icon} from './common.js';
let conversationId=null;
async function documents(){
 const rows=await api('/documents'),admin=currentUser().role==='admin';
 $('#view').innerHTML=head('KNOWLEDGE OPERATIONS','知识资产','接入企业文档，管理索引版本与部门访问范围。')+'<div class="stats">'+stat('文档总数',rows.length,'当前权限可见的知识资产')+stat('可检索',rows.filter(r=>r.searchable).length,'已有生效索引')+stat('待处理',rows.filter(r=>['queued','running','pending'].includes(r.status)).length,'由后台 Worker 持续处理')+stat('处理失败',rows.filter(r=>r.status==='failed').length,'支持保留旧版本后重试')+'</div><div class="card"><div class="toolbar"><h2>文档管理</h2><div class="actions" style="margin:0"><input id="filter" class="search" placeholder="搜索文档名称或部门" aria-label="搜索文档"><button id="refresh" class="btn small">'+icon('arrow')+' 刷新状态</button></div></div><div id="document-table"></div></div>'+(admin?'<div class="card"><h2>导入文档 / 更新版本</h2><p class="muted">支持 PDF、DOCX、Markdown、TXT，单文件不超过 16MB。新版本索引完成后才替换当前可检索版本。</p><form id="upload"><div class="grid2"><div><label>文件</label><input name="file" type="file" accept=".pdf,.docx,.md,.txt" required></div><div><label>更新对象</label><select name="document_id"><option value="">作为新文档接入</option>'+rows.map(r=>'<option value="'+r.id+'">'+esc(r.title)+'</option>').join('')+'</select></div><div><label>所属部门</label><input name="department" required maxlength="80" placeholder="如：运维"></div><div><label>业务版本</label><input name="version" required maxlength="80" placeholder="如：2026.09"></div></div><div class="actions"><button class="btn primary" type="submit">提交索引任务</button><span class="muted">上传内容保存在企业后端，不发送到 GitHub Pages。</span></div></form></div>':'');
 function draw(filter=''){
  const filtered=rows.filter(r=>(r.title+r.department).toLowerCase().includes(filter.toLowerCase()));
  $('#document-table').innerHTML=table(['文档名称','部门 / 版本','索引状态','生效状态','接入时间',...(admin?['操作']:[])],filtered.map(r=>[icon('file')+' '+esc(r.title),esc(r.department)+' / '+esc(r.version),badge(r.status),r.searchable?'<span class="badge good">已有可用索引</span>':'<span class="muted">等待索引</span>',date(r.updated_at),...(admin?['<div class="actions" style="margin:0">'+(r.status==='failed'?'<button class="btn small retry" data-id="'+r.id+'">重试</button>':'')+'<button class="btn small danger remove" data-id="'+r.id+'">删除</button></div>']:[])]));
  on('.retry',async el=>{await post('/documents/'+el.dataset.id+'/retry',{});await documents();});
  on('.remove',async el=>{if(!confirm('确认删除？此文档将立即从检索范围移除，历史版本按服务端保留策略处理。'))return;await api('/documents/'+el.dataset.id,{method:'DELETE'});await documents();});
 }
 draw();$('#filter').addEventListener('input',e=>draw(e.target.value));
 on('#refresh',documents);
 bindForm('#upload',async data=>{if(!data.get('document_id'))data.delete('document_id');await api('/documents',{method:'POST',body:data});await documents();});
}
function renderAnswer(answer){
 return '<div class="notice '+(answer.refused?'warning':'')+'">'+(answer.refused?'本次证据不足，系统已拒绝生成确定性结论。':'回答基于下方检索证据生成，请点击引用核对原文。')+'</div><div class="bodytext">'+esc(answer.answer)+'</div><div class="actions"><span class="badge">'+esc(answer.latency_ms)+' ms</span><span class="muted">会话已保存在服务端</span></div>';
}
function renderEvidence(evidence){return evidence.length?evidence.map((e,i)=>'<details class="evidence" '+(i===0?'open':'')+'><summary><strong>'+esc(e.title)+'</strong> <span class="badge">'+esc(e.department)+'</span></summary><p class="muted">版本 '+esc(e.version)+' · '+esc(e.heading)+(e.page?' · 第 '+e.page+' 页':'')+'</p><pre>'+esc(e.text)+'</pre><p class="muted">引用 ID：'+esc(e.id)+'</p></details>').join(''):empty('本次没有检索到有权访问的证据');}
async function ask(){
 $('#view').innerHTML=head('EVIDENCE-FIRST ASSISTANT','知识问答','基于企业资料回答，检索范围由登录账号的部门权限决定。','<button id="new-chat" class="btn">新建会话</button>')+'<div class="columns"><div><div class="card"><h2>向知识库提问</h2><form id="ask"><textarea name="query" required minlength="2" maxlength="2000" placeholder="描述你遇到的问题，或输入错误码、接口名称…"></textarea><div class="grid2"><div><label>指定部门（可选）</label><input name="department" placeholder="留空检索全部授权部门"></div><div><label>指定版本（可选）</label><input name="version" placeholder="留空检索生效版本"></div></div><div class="actions"><button class="btn primary" type="submit">检索并回答 '+icon('arrow')+'</button><span id="conversation-status" class="muted">'+(conversationId?'继续当前会话':'新的知识问答')+'</span></div></form></div><div class="card"><h2>回答</h2><div id="answer">'+empty('提交问题后，回答与引用证据将在这里展示')+'</div></div></div><div class="card"><div class="cardhead"><h2>参考资料</h2><span class="badge">权限过滤</span></div><p class="muted">资料中的指令不被作为系统命令执行。原文引用可追溯，不代表模型结论一定正确。</p><div id="evidence">'+empty('等待本次检索结果')+'</div></div></div>';
 on('#new-chat',async()=>{conversationId=null;await ask();});
 bindForm('#ask',async data=>{const payload={query:data.get('query')};if(conversationId)payload.conversation_id=conversationId;for(const k of ['department','version'])if(data.get(k).trim())payload[k]=data.get(k).trim();$('#answer').innerHTML='<div class="loading"><div class="spinner"></div>正在检索授权资料并生成回答</div>';const result=await post('/ask',payload);conversationId=result.conversation_id;$('#answer').innerHTML=renderAnswer(result);$('#evidence').innerHTML=renderEvidence(result.evidence);$('#conversation-status').textContent='继续当前会话';});
}
async function history(){
 const rows=await api('/conversations');
 $('#view').innerHTML=head('CONVERSATION HISTORY','问答记录','仅显示当前账号创建的会话。')+'<div class="columns"><div class="card"><h2>我的会话</h2>'+(rows.length?rows.map(r=>'<button class="listbutton conversation" data-id="'+r.id+'">'+esc(r.title)+'<small>'+date(r.created_at)+'</small></button>').join(''):empty('还没有问答记录'))+'</div><div class="card"><h2>会话详情</h2><div id="messages">'+empty('选择一个会话查看问答和引用')+'</div></div></div>';
 on('.conversation',async el=>{const messages=await api('/conversations/'+el.dataset.id);$('#messages').innerHTML=messages.map(m=>'<h3>'+esc(m.question)+'</h3>'+renderAnswer(m.response)+renderEvidence(m.response.evidence)).join('');});
}
start({id:'knowledge',brand:'Atlas Knowledge',title:'Atlas Knowledge · 企业知识平台',symbol:'file',tagline:'让企业知识<br>成为可靠的答案。',description:'统一管理知识资产，以权限为边界，以证据为依据，让每一次检索与问答都有迹可循。',defaultPage:'ask',navigation:[{id:'ask',label:'知识问答',icon:'chat'},{id:'documents',label:'知识资产',icon:'file'},{id:'history',label:'问答记录',icon:'task'},{id:'users',label:'成员与权限',icon:'users',admin:true},{id:'audit',label:'审计日志',icon:'shield',admin:true}],render:page=>({ask,documents,history}[page]())});
